
import { Trade, TradeType, AssetClass, TradeStatus, MarketCondition, Mood } from '../types';

export const MOCK_TRADES: Trade[] = [
  {
    id: 'mock-1',
    userId: 'demo', // Placeholder, will be overwritten when loading
    symbol: 'BANKNIFTY',
    assetClass: AssetClass.OPTIONS,
    type: TradeType.LONG,
    entryDate: new Date(Date.now() - 86400000 * 5).toISOString(), // 5 days ago
    entryPrice: 435.50,
    exitPrice: 480.00,
    quantity: 150, // 10 lots
    stopLoss: 415.00,
    target: 475.00,
    fees: 120,
    pnl: 6555, // (44.5 * 150) - 120
    rrRatio: 2.1,
    status: TradeStatus.CLOSED,
    setups: ['Opening Range Breakout', 'VWAP Bounce'],
    strategies: ['Intraday Momentum'],
    marketCondition: MarketCondition.TRENDING_STRONG,
    mistakes: [],
    mood: Mood.EXCITED,
    emotions: ['Confidence', 'Flow'],
    notes: 'Market opened with a gap up and sustained. Entered on the first pullback to VWAP. Clean move.',
    imageUrls: [],
    rating: 5
  },
  {
    id: 'mock-2',
    userId: 'demo',
    symbol: 'RELIANCE',
    assetClass: AssetClass.EQUITY,
    type: TradeType.SHORT,
    entryDate: new Date(Date.now() - 86400000 * 3).toISOString(),
    entryPrice: 2450.00,
    exitPrice: 2465.00,
    quantity: 100,
    stopLoss: 2460.00,
    target: 2430.00,
    fees: 50,
    pnl: -1550, // (-15 * 100) - 50
    rrRatio: 2.0,
    status: TradeStatus.CLOSED,
    setups: ['Supply Zone'],
    strategies: ['Swing'],
    marketCondition: MarketCondition.CHOPPY,
    mistakes: ['No Stop Loss', 'Revenge Trading'],
    mood: Mood.STRESSED,
    emotions: ['Fear', 'Hope'],
    notes: 'Moved stop loss hoping for a reversal. Classic mistake. Need to respect the original plan.',
    imageUrls: [],
    rating: 2
  },
  {
    id: 'mock-3',
    userId: 'demo',
    symbol: 'NIFTY',
    assetClass: AssetClass.FUTURES,
    type: TradeType.LONG,
    entryDate: new Date(Date.now() - 86400000 * 2).toISOString(),
    entryPrice: 19500,
    exitPrice: 19520,
    quantity: 50,
    stopLoss: 19480,
    target: 19550,
    fees: 100,
    pnl: 900,
    rrRatio: 2.5,
    status: TradeStatus.CLOSED,
    setups: ['Trend Continuation'],
    strategies: ['Scalping'],
    marketCondition: MarketCondition.RANGE_BOUND,
    mistakes: ['Exited Early'],
    mood: Mood.BORED,
    emotions: ['Impatience'],
    notes: 'Got bored and exited early. Market eventually hit target. Lack of patience costs money.',
    imageUrls: [],
    rating: 3
  },
  {
    id: 'mock-4',
    userId: 'demo',
    symbol: 'HDFCBANK',
    assetClass: AssetClass.EQUITY,
    type: TradeType.LONG,
    entryDate: new Date(Date.now() - 86400000 * 1).toISOString(),
    entryPrice: 1510,
    exitPrice: 1545,
    quantity: 200,
    stopLoss: 1495,
    target: 1550,
    fees: 80,
    pnl: 6920,
    rrRatio: 2.6,
    status: TradeStatus.CLOSED,
    setups: ['Breakout', 'Volume Spike'],
    strategies: ['Swing'],
    marketCondition: MarketCondition.TRENDING_MILD,
    mistakes: [],
    mood: Mood.NEUTRAL,
    emotions: ['Calm'],
    notes: 'Perfect execution. Waited for volume confirmation before entering.',
    imageUrls: [],
    rating: 5
  },
  {
    id: 'mock-5',
    userId: 'demo',
    symbol: 'CRUDEOIL',
    assetClass: AssetClass.FUTURES,
    type: TradeType.SHORT,
    entryDate: new Date(Date.now() - 3600000 * 4).toISOString(), // 4 hours ago
    entryPrice: 6500,
    exitPrice: 6500,
    quantity: 10,
    stopLoss: 6520,
    target: 6450,
    fees: 200,
    pnl: -200, // Break even gross, loss on fees
    rrRatio: 2.5,
    status: TradeStatus.BE,
    setups: ['Reversal'],
    strategies: ['Intraday'],
    marketCondition: MarketCondition.CHOPPY,
    mistakes: [],
    mood: Mood.NEUTRAL,
    emotions: ['Alert'],
    notes: 'Trade went nowhere. Scratched it before major news.',
    imageUrls: [],
    rating: 4
  }
];
